### ISSUE TITLE
Bug: "On this page" vf-navigation header activates too soon

### ISSUE THREAD

**Issue by spivass81** [visual-framework/vf-core#1757] opened 2022-02-11 12:32 UTC
Noticed an issue with the "On this page" vf-navigation component, the menu items get activated too early while scrolling.
I am attaching a screen shot below to showcase. @nitinja let me know if it's not clear enough what the issue is.

<img width="1053" alt="Screenshot 2022-02-11 at 13 18 13" src="https://user-images.githubusercontent.com/50863581/153590395-f1050a4b-d304-4c8a-8ced-7b9a2aa387ec.png">

Here a page the uses this component:

https://www.embl.org/sites/hamburg/

Also, another thing. When you click on the individual vf-navigation__items which are set as anchor links, the browser takes you to the correct section, but it should stop a bit higher. For example, on the same page, the anchor link for research takes you here:

<img width="994" alt="Screenshot 2022-02-11 at 13 22 12" src="https://user-images.githubusercontent.com/50863581/153591389-7e9db187-a6d9-4aab-8c58-3a448f2cf76a.png">

while it should take you here:

<img width="1021" alt="Screenshot 2022-02-11 at 13 22 26" src="https://user-images.githubusercontent.com/50863581/153591568-4e05ec01-21b4-41c4-b4e0-16963e9c1927.png">

This seems to work fine when the anchor is set in vf-card-container, for example:

https://www.embl.org/sites/hamburg/#topics

https://www.embl.org/sites/hamburg/#services

But not when the anchor is set in embl-grid

https://www.embl.org/sites/hamburg/#research

https://www.embl.org/sites/hamburg/#seminars

Let me know if this clear enough

**Comment by sandykadam** [comment] 2022-02-11 12:41
@spivass81 Is this page https://www.embl.org/sites/hamburg/#seminars created manually or from Wordpress block, because I think issue is because the "section" tags are not correctly closed. Please find attached screenshot, there are 2 section tag red & blue marked, we can see only one is closing, other one is missing.

![Screenshot 2022-02-11 at 12 38 14](https://user-images.githubusercontent.com/1227241/153593107-da495740-2b90-4d32-a5f3-50c141d2d9de.png)

**Comment by nikiforosk** [comment] 2022-07-04 13:44
@spivass81 Can you please let me know if this issue has been resolved?

**Comment by spivass81** [comment] 2022-07-05 10:42
Hey @nikiforosk, this is still pending, I will try Sandeep's suggestion once I'll get a chance, but I don't think that it will solve the issue (I think I gave it a go a while ago and didn't work).

**Comment by nikiforosk** [comment] 2022-07-13 10:52
@spivass81 Have you had the chance to try Sandeep's solution again?

**Comment by spivass81** [comment] 2022-07-18 13:48
Hi @nikiforosk sorry lost track of this because I was getting the notifications to my personal email address, have now added my embl email address instead, I should react more timely from now on. 

Regarding this topic, I have closed the the section tag as @sandykadam suggested the issue seems to remain though:

https://www.embl.org/sites/hamburg/

<img width="1101" alt="Screenshot 2022-07-18 at 15 45 44" src="https://user-images.githubusercontent.com/50863581/179525730-f44d572e-ec8c-4d5d-b46b-b3658871e76e.png">

@sandykadam let me know if I missed anything.

**Comment by spivass81** [comment] 2022-07-26 18:52
@sandykadam I have documented two different topics here and I would like to break them to two separate tickets. Could you please let me know to which one of the two issues your fix suggestions refers to?

**Comment by sandykadam** [comment] 2022-08-11 12:12
@spivass81 With recent release of navigation @pacope92  have updated the EMBL DEV site and the tab navigation is working fine. Can you please also check and confirm. https://wwwdev.embl.org/sites/barcelona/

If you think it is working we can push to prod.

**Comment by spivass81** [comment] 2022-08-11 12:59
Hey @sandykadam this is great!!

I tried the sites landing pages, seems to be working great there, both issues flagged in this ticket are fixed.

I have also checked a couple of other pages with this feature, where I still notice some issues:<br>
For example:

embl.org/about/
The "Public engagement and outreach" tab doesn't get activated at all, and also activation of tabs while scrolling is inconsistent.

embl.org/covid19
Scrolling issue here is solved, however the section header is still hidden when you click on the tab.

Are there any changes that have to be applied on the page page level as well or the fix will be applied automatically to all pages that use this feature? Let me know if anything is unclear. Happy to have a quick call to clarify if needed.

**Comment by francisco-ebi** [comment] 2022-08-11 13:20
Hi @spivass81
For the 1st issue, I noticed it's caused by a duplicated id
![Screenshot 2022-08-11 at 14 13 32](https://user-images.githubusercontent.com/5340971/184142137-2ded40d9-4066-425a-83b4-a809c4f784d0.png)

the second id I have highlighted with red color is causing the issue and if it's updated to `public-engagement-outreach` will solve it.
For the 2nd issue, could you verify the url is: https://wwwdev.embl.org/topics/coronavirus/. I double checked there and it's working fine in my end.
Thanks.

**Comment by spivass81** [comment] 2022-08-11 14:51
Super, many thanks for your feedback @pacope92 all clear, I will clean the duplicate id from the "About" page, and for the Covid19 page, indeed, it is working fine (I must have confused this with the production page, my apologies).

So, the changes can move to production I guess, I didn't notice anything else and the fixes seem to be working fine!

Many many thanks again guys!!

**Comment by francisco-ebi** [comment] 2022-08-24 09:51
This is now deployed to production, closing this ticket

**Closed as completed by francisco-ebi** 2022-08-24 09:51 UTC
