### ISSUE TITLE
DOCS: Add Colour Palette as part of documentation

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#278] opened 2019-03-04 15:20 UTC
As part of the documentation rather than updating the design tokens 'package'.

Create an auto-updating colour palette of the colours for:

- the visual framework UI colours
- the (EMBL) visual framework colours

These should include RGB, HEX colours.

It'd be neat to show which colours to have for text in regards to a11y.

The documentation page should generate the colour palettes by looking for the `.yml` files and creating the correct palette and layout.

There's probably some Handlebars/JavaScript/Sass jiggery-pokery required for this.

**Comment by khawkins98** [comment] 2019-03-04 18:29
My first thought would be if the design tokens could also be output to a json file.

**Comment by khawkins98** [comment] 2019-03-04 18:34
I'll flush that out a bit more; I guess there are two approaches:

1. We could instead [do our Theo-based design tokens as JSON](https://github.com/salesforce-ux/theo#spec) (and not YAML), and then just read that file directly with some JS
2. Use gulp to translate the YAML to JSON and use that output. https://www.npmjs.com/package/gulp-yaml

**Comment by sturobson** [comment] 2019-03-04 18:35
I don't see why they couldn't be. 

I guess ideally we would want this to have as few moving parts as possible. So, if we can get it done with `.yml` do that … of course the other thing is to transpose the design tokens into `json`. 

I don't think that would be a good idea as then we will have a component library with two types of 'where data is stored'.

So - if we can automate to generate the .json (and delete after?) or find something that would do it in .yml that'd be great.

**Comment by sturobson** [comment] 2019-03-04 18:36
> We could instead do our Theo-based design tokens as JSON (and not YAML), and then just read that file directly with some JS

As mentioned: I don't think having one thing using `.json` when every other thing is using `.yml` within the component library is a good thing.

> Use gulp to translate the YAML to JSON and use that output.

I think we go with this, unless we can find something that'd do it with .yml

**Comment by sturobson** [comment] 2019-03-04 18:37
I did 'make this work' with inline `.yml` in the `.md` file when I worked with Monotype. Of course we'd want to forgo the inlining by hand of the key/value pairs for colours - because … well, that's not really maintainable or automated :D

**Comment by khawkins98** [comment] 2019-03-04 18:48
Let's assume there's a way to feed Yaml/Json into our list of colours; where does that documentation live?

Idea:

1. We move `components/vf-design-tokens/core.palette.alias.yml` into a new `vf-colors` pattern
    - bonus: colours could be more easily overridden by vf-child-template themes
2. `vf-colors` contain some JS magic to display the color gallery, add documentation on usage
3. Colour documentation can then be accessed by view that (`vf-colors`) pattern

**Comment by sturobson** [comment] 2019-03-04 18:52
From what I’ve seen mentioned in the fractal slack, and from some developers I know. They put the logic stuff in the docs folder. I’m wary of moving the colours outside of design tokens. 

Abstraction upon abstraction upon abstraction. Yuk.

**Comment by khawkins98** [comment] 2019-03-04 19:29
Maybe we need to make `vf-desing-tokens` a real pattern and call it something like `vf-fundementals` where we could have auto-generated docs on:

- colour
- typography
- button radius
- breakpoints
- ... etc, all the design token stuff that is currently "invisible" in the library

We could facilitate that by
```
  - name: vf-ui-color--gray
    value: '{!color-ui-gray}'
    documentation: "Text on how to use/not use.... perhaps even an external `vf-ui-color--gray.md` file"
    meta:
      friendlyName: UI Grey
```

**Comment by sturobson** [comment] 2019-03-04 20:40
I think we shouldn't over complicate the idea of "design tokens" as they're really only for 'consumption', if that makes sense.

So we need to work out where/how we're going to consume that information into either the existing documentation site or the 'new' one ... and that may require, `yet-another-npm-package`...

I mean, Theo can auto-generate the HTML, given a little push, this is what Shopify do for their design tokens one-pager which is from their design tokens repo: https://shopify.github.io/polaris-tokens/

**Comment by markboulton** [comment] 2019-03-04 20:43
I just put this in Slack, but then saw this thread...

Mark Boulton [8:40 PM]
Dumping this in here for @Stu Robson and @Ken Hawkins following discussions yesterday on design tokens. After a bit of a request for help on Twitter, someone posted this: https://github.com/dfernandez79/ase-util
dfernandez79/ase-util
Utility library to handle Adobe Swatch Exchange (ASE) files
Stars
10
Language
JavaScript
dfernandez79/ase-utilJul 20th, 2015Added by GitHub

This is a library to convert ASE files into Json.
So, the wrong way around for us, but a question…
Could we have the ASE file as the source of truth for the colour palettes that then – through this library – outputs JSON as our design tokens automatically?
That way, any changes to the shared ASE files (which would be shared across the design team and more widely with EBI) would then trickle down. My only concern there would be screen colours being generated in a print environment.
So, we might be over complicating everything for something that simply won’t change that often.
Premature abstraction. Or something.

**Comment by khawkins98** [comment] 2019-03-04 21:06
Dropping a link for a tool for design tokens to Adobe and Sketch palettes. https://github.com/kaelig/tokens2palettes-example/blob/master/README.md

**Comment by khawkins98** [comment] 2019-07-01 09:35
Believe this is a duplicate of #315, closing.

**Closed by khawkins98** 2019-07-01 09:35 UTC
Labels: Type: Documentation
