### ISSUE TITLE
Create documentation for browser support

### ISSUE THREAD

**Issue by peter-walter** [visual-framework/vf-core#1202] opened 2020-10-29 21:59 UTC

**Comment by sturobson** [comment] 2020-10-30 08:52
Current documentation from VF1.x 

http://wwwdev.ebi.ac.uk/style-lab/websites/meta-patterns/browser-compatibility.html

**Comment by khawkins98** [comment] 2020-10-30 08:53
As part of this would be good to gather browser usage stats for:

- [x] EBI.ac.uk
- [x] EMBL.org
- [x] Major scientific service using VF 2.0
- [ ] Bonus: EMBL.de

Might be others, but that should probably be more than enough "fact-finding".

I know @sturobson is also gathering some examples of prominent support policies -- I think most go like "Last 2 versions of major browsers get gold support, everything else from last 5 years (also IE 11) get a usable experience"

- [ ] Todo: Define what "usable" is

**Comment by sturobson** [comment] 2020-10-30 09:28
Just some 'titbits': 

The 7 year old IE11 has been given it's 'end of life' dates - https://death-to-ie11.com

Microsoft is starting to drop support for it already - https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

I also remember seeing a tweet, maybe an article - about new Edge having a 'Legacy Mode' for people that are stuck on IE11 because of the proprietary software they're using. The Edge team will actively help you move to this mode in Edge rather than use IE11. I'll ping some Microsoft folks I know if I cannot find it.

**Comment by khawkins98** [comment] 2020-10-30 12:00
Some stats for 1 Aug - 29 Oct 2020 users.

## EMBL.org

Browser | Note | Traffic %
-- | -- | --
Chrome | 62 and older account for less than 1% | 54.66%
Safari | 11 and older account for less than 1% | 17.84
Firefox |  77 and older account for less than 1% | 9.57
Safari (in-app) | | 4.96
Android Webview | 83 and older account for less than 1%   | 4.29
Edge (chromium) |   | 2.51
Edge classic |   | 1.30
Samsung | 11 and older account for less than 1%  | 1.86
IE | 8, 9, 10 acount for less than 0.3% | 1.35
Opera (desktop) | 69 and older account for less than 0.1%  | 0.60


## EBI.ac.uk

Browser | Note | Traffic %
-- | -- | --
Chrome | 63 and older account for less than 1% | 65.73%
Safari | 11 and older account for less than 1% | 11.70
Firefox |  77 and older account for less than 1% | 11.27
Edge (chromium) |   | 3.72
Edge classic |   | 2.11
Android Webview | 83 and older account for less than 0.2%   | 1.37
IE | 8, 9, 10 acount for less than 0.1% | 1.59
Opera (desktop) | 69 and older account for less than 0.2%  | 0.74
Samsung | 11 and older account for less than 0.1%  | 0.73
Safari (in-app) | | 0.33

## Representative major scientific service

(I don't have direct access to the raw data so it's less granular, but still informative)

Browser | Note | Traffic %
-- | -- | --
Chrome |  | 55.96%
Safari |  | 15.21
Firefox |  |  10.66
Edge (chromium and classic)  |   | 5.36
IE | | 4.25
Safari (in-app) | | 2.50
Android Webview |   | 2.40
Samsung |  | 1.63
UC Browser |  | 0.84
Opera (desktop) |  | 0.83

**Comment by khawkins98** [comment] 2020-10-30 12:03
The most interesting thing here is that the IE 11 usage trends higher on the scientific services than the corporate sites (this is typical from past reviews as well). However, IE 11 is still well below 1 in 20 users (5%) in all cases.

By my view, that makes it reasonable to say "We focus our efforts on supporting major browsers in use by 95%+ of our audiences, and we ensure the site is navigable and usable by the remaining 5%"

**Comment by khawkins98** [comment] 2020-10-30 12:11
I think we can also steal some language from the EBI VF 1.x page (as @sturobson linked to), things like:

> For browser support, aim for content and functionality to be unobstructed on browsers released within the last five years and have JavaScript enabled; this is represents virtually all users of the EMBL-EBI site (in excess of 99.9%).
> 
> As a guiding rule, test for compatibility on any browser or device that represents more than 2% of the usage of www.ebi.ac.uk.
> 
> As intended by the CSS specification, not all browsers, devices, or users render content to look exactly the same. Our aim is to create an accessible and visually consistent design across a broad range of clients, not pixel-perfect designs. Further, we build atop the basic functionality, adding progressive-enhancement features to newer classes of browsers and devices.
>

**Comment by khawkins98** [comment] 2020-10-31 20:06
Related: Fallback support should be IE only #734

**Comment by sturobson** [comment] 2020-11-01 09:40
I forgot about that.

It’s a shame IE10 and 11 no longer support the `if` meta tag things - otherwise we could bundle all this up in a separate CSS file. 

Although - the things like `vf-grid` and `embl-grid` fall back to flex box - so it’s more than IE specific really.

**Comment by khawkins98** [comment] 2020-12-15 13:31
Stub documentation at: https://latest.visual-framework.dev/guidance/browser-support/

**Comment by khawkins98** [comment] 2021-02-03 16:56
Dumping some thoughts I've had:

We classify browsers into two categories:

1. Modern and mainstream browsers released within the last 3 years and with more than 5% user base of the VF (Chrome, FF, Safari, Chromium Edge, etc.)
  - For these we actively test and where possible strive to write visual regression testing as possible (*note we do not yet have a tool in place, but are experimenting)
2. Legacy and minor browsers older than 3 years or with less than 5% user base (IE 11, pre-Chromium Edge)
  - For these we do not actively monitor but will address support requests as best we can
  - We also acknowledge that life science services can have specific use cases by institutions. Those use cases can be addressed on a case-by-case basis and the VF will avoid doing anything that actively breaks older browsers.

Going to try to pick this up this week.

**Closed as completed** 2021-02-05 15:23 UTC
